apiVersion: apps/v1
kind: Deployment
metadata:
  name: scotia-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: scotia-app
  template:
    metadata:
      labels:
        app: scotia-app
    spec:
      containers:
      - name: scotia-container
        image: raja1021/scotia-app:latest
        ports:
        - containerPort: 8080
